/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hat.glb --transform 
Files: hat.glb [3.31MB] > C:\Users\chris\dash-portfolio\hat-transformed.glb [1.12MB] (66%)
*/

"use client";

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame, extend } from '@react-three/fiber';
import { AmbientLight, DirectionalLight } from 'three'; // Import lights

// Extend fiber with DirectionalLight
extend({ AmbientLight, DirectionalLight });

export default function Wizard(props) {
  const group = useRef();
  const { nodes, animations } = useGLTF('/models/hat-transformed.glb');
  const { actions } = useAnimations(animations, group);

  const modelRef = useRef();
  useFrame((state, delta, xrFrame) => {
    modelRef.current.rotation.y += 0.2 * delta;
  });

  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, 0]} scale={[0.6, 0.6, 0.6]}
    rotation={[0.4,-1,0]}>
      {/* Ambient light */}
      <ambientLight intensity={1.5} />
      
      {/* Directional light */}
      <directionalLight color="#ffffff" intensity={20} position={[5, 5, 5]} />

      <group  ref={modelRef}>
        <group name="RootNode" scale={0.918}>
          <group name="pCylinder3" position={[1.654, 0.192, -1.15]} rotation={[-Math.PI / 9, 0, Math.PI / 2]} scale={[0.075, 0.15, 0.075]}>
            <group name="pCube134" position={[17.195, 11.027, -2.966]} rotation={[0, 0.14, -Math.PI / 2]} scale={[23, 26, 0.133]}>
              <mesh name="pCube134_blinn1_0" geometry={nodes.pCube134_blinn1_0.geometry} material={nodes.pCube134_blinn1_0.material} />
            </group>
            <group name="pCylinder2" position={[0, 22.053, 0]}>
              <mesh name="pCylinder2_phong1_0" geometry={nodes.pCylinder2_phong1_0.geometry} material={nodes.pCylinder2_phong1_0.material} />
            </group>
            <group name="pCube4" position={[15.072, 11.027, -2.725]} rotation={[0, -1.431, -Math.PI / 2]} scale={[24, 0.667, 32]}>
              <mesh name="pCube4_phong1_0" geometry={nodes.pCube4_phong1_0.geometry} material={nodes.pCube4_phong1_0.material} />
            </group>
            <mesh name="pCylinder3_phong1_0" geometry={nodes.pCylinder3_phong1_0.geometry} material={nodes.pCylinder3_phong1_0.material} />
          </group>
        </group>
        <mesh name="pCylinder1_phong1_0" geometry={nodes.pCylinder1_phong1_0.geometry} material={nodes.pCylinder1_phong1_0.material} position={[0, 0.176, -1.055]} rotation={[-0.384, 0, Math.PI / 2]} scale={[0.069, 1.376, 0.069]} />
        <mesh name="pCube6_lambert1_0" geometry={nodes.pCube6_lambert1_0.geometry} material={nodes.pCube6_lambert1_0.material} position={[-1.599, 0.138, 0.335]} scale={[0.092, 0.009, 0.073]} />
        <mesh name="pCube7_phong3_0" geometry={nodes.pCube7_phong3_0.geometry} material={nodes.pCube7_phong3_0.material} position={[1.599, 0.138, 0.335]} scale={[0.092, 0.009, 0.073]} />
        <mesh name="pCube3_phong2_0" geometry={nodes.pCube3_phong2_0.geometry} material={nodes.pCube3_phong2_0.material} position={[-1.487, 0.17, -0.578]} scale={[0.092, 0.046, 0.069]} />
        <mesh name="pCube135_phong4_0" geometry={nodes.pCube135_phong4_0.geometry} material={nodes.pCube135_phong4_0.material} position={[0, 0.179, 0.702]} scale={[0.642, 0.001, 0.367]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hat-transformed.glb')
