/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 staff.glb --transform 
Files: staff.glb [4.27MB] > C:\Users\chris\dash-portfolio\staff-transformed.glb [3.28MB] (23%)
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function StaffModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/staff-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/staff-transformed.glb')
