/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 wizard.glb --transform 
Files: wizard.glb [11.55MB] > C:\Users\chris\dash-portfolio\wizard-transformed.glb [645.85KB] (94%)
*/
"use client";

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame, extend } from '@react-three/fiber';
import { AmbientLight, DirectionalLight } from 'three'; // Import lights

// Extend fiber with DirectionalLight
extend({ AmbientLight, DirectionalLight });

export default function Wizard(props) {
  const group = useRef();
  const { nodes, animations } = useGLTF('/models/wizard-transformed.glb');
  const { actions } = useAnimations(animations, group);

  const modelRef = useRef();
  useFrame((state, delta, xrFrame) => {
    modelRef.current.rotation.y += 0.2 * delta;
  });

  return (
    <group ref={group} {...props} dispose={null} position={[0, -0.9, 0]} scale={[1.3, 1.3, 1.3]}>
      {/* Ambient light */}
      <ambientLight intensity={1.5} />
      
      {/* Directional light */}
      <directionalLight color="#ffffff" intensity={20} position={[5, 5, 5]} />
      <group 
       ref={modelRef}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} position={[-0.724, 1.013, 0.657]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} position={[-0.724, 1.013, 0.762]} scale={0.092} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} position={[0.048, 0.928, 0.305]} scale={0.605} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} position={[0.048, 0.928, 0.305]} scale={0.605} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} position={[0.048, -0.002, 0.572]} scale={0.605} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} position={[0.011, 0.442, 1.214]} scale={[0.026, 0.245, 0.026]} />
        <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} position={[0.808, 1.239, 0.49]} scale={0.605} />
        <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} skeleton={nodes.Object_30.skeleton} position={[0, 0.725, 1.241]} rotation={[0, 1.571, 0]} scale={0.01} />
        <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} skeleton={nodes.Object_31.skeleton} position={[0, 0.725, 1.241]} rotation={[0, 1.571, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/wizard-transformed.glb')
